[build]
	publish = "public/"
	command = "npm run build"

[build.processing.html]
	pretty_urls = true

[[redirects]]
	from = "https://elijah-sh.netlify.app/*"
	to = "https://elijah.sh/:splat"
	status = 301
	force = true
